### ISSUE TITLE
Can you show me your training results?

### ISSUE THREAD

**Issue by BestPolarBear** [timoklein/car_racer#6]
I run carracing with sac algorithm in my own project, and the effect is very poor.

I ran your code and found that the results were also very poor. Can you show me your training results (distance, reward)?

**Comment by timoklein** [comment]
Hey there,
some results with the best trained model are described in the write up (link is in the readme).

Honestly though, this was a university project and the first time all people involved worked with Reinforcement Learning. That means there's probably some things missing in the code. For instance, I don't think we ever implemented frame stacking ([here's a link with more info](https://danieltakeshi.github.io/2016/11/25/frame-skipping-and-preprocessing-for-deep-q-networks-on-atari-2600-games/)). If you really want to get strong results with this codebase, that's the minimum thing you will have to implement on top of it.

Sorry for the lame reply :/
